name: PR Check mit neuen Dateien

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check_new_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          cd data-fetching
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script to list new files in PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          python data-fetching/pull_request_check.py
