name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          cd pluigin-data-pull
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Falls du ein requirements.txt hast

      - name: Run script
        run: python pluigin-data-pull/main.py
